#
#  Makefile for TKWATM test script generation and execution for Emergency Booking
#
ROOT=$(TKWROOT)/config/FHIR_111_UEC/autotest_config
MERGEDTSTPFILE=$(ROOT)/mergedfile.tstp

clean: 
	rm -f $(MERGEDTSTPFILE)
	rm -rf autotest_logs/*
	rm -rf auto_tests/*
	rm -rf tst/*
