#
#  docker-compose file supporting a docker stack comprised of a 
#  111_uec consumer simulator (provider test suite) instance 
#
version: "3"
services:
  tkw_uec_consumer_simulator:
    image: nhsdigitalmait/tkw_uec_consumer_simulator:0.1

    environment:
      - TZ=Europe/London

    network_mode : "host"

    volumes:
        # <host path to mount> : <mount point within docker>
        # auto_tests folder
        - ${TKWROOT}/config/FHIR_111_UEC/autotest_config/auto_tests:/TKW_ROOT/config/FHIR_111_UEC/autotest_config/auto_tests
        # endpoint_configs folder
        - ${TKWROOT}/config/FHIR_111_UEC/autotest_config/endpoint_configs:/TKW_ROOT/config/FHIR_111_UEC/autotest_config/endpoint_configs
        # autotest logs folder
        - ${TKWROOT}/config/FHIR_111_UEC/autotest_config/autotest_logs:/TKW_ROOT/config/FHIR_111_UEC/autotest_config/autotest_logs
